[package]
name = "anomaly"
version = "0.1.0"
authors = ["Kelson Ball <kelson.j.ball@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
affine_transforms = "0.3.0"